// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Compose 供 Wails 前端呼叫。
 * Wails 會將 Go error 傳回前端 Promise rejection。
 */
export function Compose(inputVideo: string, inputVideoWidth: number, inputVideoHeight: number, frameImage: string, frameImageWidth: number, frameImageHeight: number, outputVideo: string): $CancellablePromise<void> {
    return $Call.ByID(3292587877, inputVideo, inputVideoWidth, inputVideoHeight, frameImage, frameImageWidth, frameImageHeight, outputVideo);
}
